/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Deck_viewer.graphql
 * @generated SignedSource<<6402b43f045fcf13b0000656470449c8>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Deck_viewer = {|
  +id: string;
  +playerPosition: number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Deck_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "playerPosition",
      "storageKey": null
    }
  ],
  "type": "Game"
};

module.exports = fragment;
