/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Deck_viewer.graphql
 * @generated SignedSource<<b11c7cc87ab30453893c8c71884d7d07>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Deck_viewer = {|
  +gameId: string;
  +player: ?{|
    +position: number;
  |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Deck_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "gameId",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "PlayerView",
      "name": "player",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "position",
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Game"
};

module.exports = fragment;
