/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Game_viewer.graphql
 * @generated SignedSource<<9eb869962c83769e4d6beac58aad6713>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Game_viewer = {| |};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Game_viewer",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "PlayerList_viewer",
      "args": null
    },
    {
      "kind": "FragmentSpread",
      "name": "Hand_viewer",
      "args": null
    },
    {
      "kind": "FragmentSpread",
      "name": "FaceUpCards_viewer",
      "args": null
    },
    {
      "kind": "FragmentSpread",
      "name": "Board_viewer",
      "args": null
    },
    {
      "kind": "FragmentSpread",
      "name": "Deck_viewer",
      "args": null
    }
  ],
  "type": "Game"
};

module.exports = fragment;
