/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule GameUIQuery.graphql
 * @generated SignedSource<<b9a28c98e89ce32b95cdbcde6d204165>>
 * @relayHash 1704c2f7f3af9f573c21ccb46c715093
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query GameUIQuery(
  $gameId: ID!
  $player: Int!
) {
  game(id: $gameId, player: $player) {
    ...PlayerList
    ...Hand
    ...FaceUpCards
    ...Board
  }
}

fragment PlayerList on Game {
  players {
    ...Player
  }
  player_position
}

fragment Hand on Game {
  hand {
    ...Card
  }
  player_position
}

fragment FaceUpCards on Game {
  face_up_cards {
    ...Card
  }
}

fragment Board on Game {
  board {
    cities {
      key
      name
      x
      y
    }
    routes {
      cities
      length
      color
    }
  }
}

fragment Card on Card {
  position
  color
}

fragment Player on Player {
  position
  name
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "gameId",
        "type": "ID!",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "player",
        "type": "Int!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "GameUIQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "id",
            "variableName": "gameId",
            "type": "ID!"
          },
          {
            "kind": "Variable",
            "name": "player",
            "variableName": "player",
            "type": "Int!"
          }
        ],
        "concreteType": "Game",
        "name": "game",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "PlayerList",
            "args": null
          },
          {
            "kind": "FragmentSpread",
            "name": "Hand",
            "args": null
          },
          {
            "kind": "FragmentSpread",
            "name": "FaceUpCards",
            "args": null
          },
          {
            "kind": "FragmentSpread",
            "name": "Board",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "GameUIQuery",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "gameId",
        "type": "ID!",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "player",
        "type": "Int!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "GameUIQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "id",
            "variableName": "gameId",
            "type": "ID!"
          },
          {
            "kind": "Variable",
            "name": "player",
            "variableName": "player",
            "type": "Int!"
          }
        ],
        "concreteType": "Game",
        "name": "game",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Player",
            "name": "players",
            "plural": true,
            "selections": [
              {
                "kind": "InlineFragment",
                "type": "Player",
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "position",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "name",
                    "storageKey": null
                  }
                ]
              }
            ],
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "player_position",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Card",
            "name": "hand",
            "plural": true,
            "selections": [
              {
                "kind": "InlineFragment",
                "type": "Card",
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "position",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "color",
                    "storageKey": null
                  }
                ]
              }
            ],
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Card",
            "name": "face_up_cards",
            "plural": true,
            "selections": [
              {
                "kind": "InlineFragment",
                "type": "Card",
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "position",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "color",
                    "storageKey": null
                  }
                ]
              }
            ],
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Board",
            "name": "board",
            "plural": false,
            "selections": [
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "City",
                "name": "cities",
                "plural": true,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "key",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "name",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "x",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "y",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              },
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "Route",
                "name": "routes",
                "plural": true,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "cities",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "length",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "color",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query GameUIQuery(\n  $gameId: ID!\n  $player: Int!\n) {\n  game(id: $gameId, player: $player) {\n    ...PlayerList\n    ...Hand\n    ...FaceUpCards\n    ...Board\n  }\n}\n\nfragment PlayerList on Game {\n  players {\n    ...Player\n  }\n  player_position\n}\n\nfragment Hand on Game {\n  hand {\n    ...Card\n  }\n  player_position\n}\n\nfragment FaceUpCards on Game {\n  face_up_cards {\n    ...Card\n  }\n}\n\nfragment Board on Game {\n  board {\n    cities {\n      key\n      name\n      x\n      y\n    }\n    routes {\n      cities\n      length\n      color\n    }\n  }\n}\n\nfragment Card on Card {\n  position\n  color\n}\n\nfragment Player on Player {\n  position\n  name\n}\n"
};

module.exports = batch;
