/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Hand_viewer.graphql
 * @generated SignedSource<<fca62681cd188c9bfaef54cbbe9e381b>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Hand_viewer = {|
  +player: ?{|
    +position: number;
    +hand: ?{|
      +edges: ?$ReadOnlyArray<?{|
        +node: ?{| |};
      |}>;
    |};
  |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": {
    "connection": [
      {
        "count": null,
        "cursor": null,
        "direction": "forward",
        "path": [
          "player",
          "hand"
        ]
      }
    ]
  },
  "name": "Hand_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "PlayerView",
      "name": "player",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "position",
          "storageKey": null
        },
        {
          "kind": "LinkedField",
          "alias": "hand",
          "args": null,
          "concreteType": "CardConnection",
          "name": "__Hand_hand_connection",
          "plural": false,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "CardEdge",
              "name": "edges",
              "plural": true,
              "selections": [
                {
                  "kind": "LinkedField",
                  "alias": null,
                  "args": null,
                  "concreteType": "Card",
                  "name": "node",
                  "plural": false,
                  "selections": [
                    {
                      "kind": "FragmentSpread",
                      "name": "Card_card",
                      "args": null
                    }
                  ],
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Game"
};

module.exports = fragment;
