/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Hand_viewer.graphql
 * @generated SignedSource<<d2356ca93fbac2de0bb8e1dd56f5251b>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Hand_viewer = {|
  +hand: ?{|
    +edges: ?$ReadOnlyArray<?{|
      +node: ?{| |};
    |}>;
  |};
  +playerPosition: number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": {
    "connection": [
      {
        "count": null,
        "cursor": null,
        "direction": "forward",
        "path": [
          "hand"
        ]
      }
    ]
  },
  "name": "Hand_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": "hand",
      "args": null,
      "concreteType": "CardConnection",
      "name": "__Hand_hand_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "CardEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Card",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "FragmentSpread",
                  "name": "Card_card",
                  "args": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "playerPosition",
      "storageKey": null
    }
  ],
  "type": "Game"
};

module.exports = fragment;
