/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Hand.graphql
 * @generated SignedSource<<16c5a8975ce54fb9aa0d1e49c6335e80>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Hand = {|
  +hand: $ReadOnlyArray<?{| |}>;
  +player_position: number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Hand",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Card",
      "name": "hand",
      "plural": true,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "Card",
          "args": null
        }
      ],
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "player_position",
      "storageKey": null
    }
  ],
  "type": "Game"
};

module.exports = fragment;
