/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Player_player.graphql
 * @generated SignedSource<<fbbaa86b4c7b4b396bd2d13ac383b709>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Player_player = {|
  +position: number;
  +name: string;
  +handSize: ?number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Player_player",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "position",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "name",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "handSize",
      "storageKey": null
    }
  ],
  "type": "Player"
};

module.exports = fragment;
