/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PlayerList.graphql
 * @generated SignedSource<<6db0fda51f4c841631a19552fb3b4354>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type PlayerList = {|
  +players: $ReadOnlyArray<?{| |}>;
  +player_position: number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "PlayerList",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Player",
      "name": "players",
      "plural": true,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "Player",
          "args": null
        }
      ],
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "player_position",
      "storageKey": null
    }
  ],
  "type": "Game"
};

module.exports = fragment;
