/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Player.graphql
 * @generated SignedSource<<41ebfc0c2ffaf8cc4ec33bef66e7d3e8>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Player = {|
  +position: number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Player",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "position",
      "storageKey": null
    }
  ],
  "type": "Player"
};

module.exports = fragment;
